# frozen_string_literal: true

module Kotoshu
  module Grammar
    # Byte-level BPE tokenizer for GPT-2-style vocabularies
    # (distilroberta and friends) — the Ruby twin needed to run the
    # grammar tagger fully locally through onnxruntime.
    #
    # Ids are exactly what HuggingFace produces; the spec replays a
    # fixture generated by the reference tokenizer (byte-identical).
    class ByteBpe
      PRETOKENIZE = /'(?:s|t|re|ve|m|ll|d)| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+/
      BOS = 0
      EOS = 2

      # GPT-2 byte-to-unicode table: printable ranges map to
      # themselves; the remaining 68 bytes map upward from U+0100.
      BYTE_ENCODER = begin
        table = {}
        printable = ((33..126).to_a + (161..172).to_a + (174..255).to_a)
        n = 0
        (0..255).each do |b|
          table[b] = [printable.include?(b) ? b : 256 + n].pack("U")
          n += 1 unless printable.include?(b)
        end
        table.freeze
      end

      # @param vocab_path [String] vocab.json
      # @param merges_path [String] merges.txt
      def initialize(vocab_path, merges_path)
        require "json"
        @vocab = JSON.parse(File.read(vocab_path))
        @merges = {}
        File.foreach(merges_path).with_index do |line, i|
          next if i.zero? # version header

          pair = line.split(" ")
          @merges[[pair[0], pair[1]]] = i - 1 if pair.length == 2
        end
        @cache = {}
      end

      # Token ids for a word list (HF is_split_into_words semantics:
      # words encode BARE — no prefix spaces — verified against the
      # reference fixture).
      #
      # @param words [Array<String>]
      # @return [Array<Integer>] with BOS/EOS framing
      def encode_words(words)
        ids = [BOS]
        words.each { |w| ids.concat(word_ids(w.to_s)) }
        ids << EOS
        ids
      end

      # Token ids for raw text.
      #
      # @param text [String]
      # @return [Array<Integer>] with BOS/EOS framing
      def encode(text)
        ids = [BOS]
        text.scan(PRETOKENIZE) { |piece| ids.concat(word_ids(piece)) }
        ids << EOS
      end

      # Word-piece alignment for encode_words output: word_ids[i] is
      # the word index owning output position i (nil for BOS/EOS).
      #
      # @param words [Array<String>]
      # @return [Array<Integer, nil>]
      def alignment(words)
        align = [nil]
        words.each_with_index do |w, i|
          align.concat(word_ids(w.to_s).map { i })
        end
        align << nil
        align
      end

      # Attention mask is all ones (no padding in single-sentence use).
      def mask_for(ids)
        ids.map { 1 }
      end

      private

      def word_ids(piece)
        @cache[piece] ||= encode_piece(piece)
      end

      def encode_piece(piece)
        chars = piece.bytes.map { |b| BYTE_ENCODER[b] }
        parts = chars.map(&:to_s)
        while parts.length > 1
          pair = parts.each_cons(2).min_by { |a, b| @merges[[a, b]] || Float::INFINITY }
          rank = @merges[pair]
          break if rank.nil?

          merged = pair.join
          parts = merge_pair(parts, pair, merged)
        end
        parts.filter_map { |p| @vocab[p] }
      end

      def merge_pair(parts, pair, merged)
        out = []
        i = 0
        while i < parts.length
          if i < parts.length - 1 && parts[i] == pair[0] && parts[i + 1] == pair[1]
            out << merged
            i += 2
          else
            out << parts[i]
            i += 1
          end
        end
        out
      end
    end
  end
end
